keyboards:imk64:jactry: Add a custom key CK_OSMD for switching system mode and some system-specific settings.
Huckies/qmk_port_ch582 pull request #109
Opened 2023-05-19 15:36 UTC by jactry

2023-05-24 02:41 UTC, Huckies requested changes

2023-05-24 02:41 UTC, Huckies commented on qmk_porting/keyboards/imk64/keymaps/jactry/keymap.c
> +    CK_OSMD = SAFE_RANGE,
With reference to [this](https://github.com/O-H-M2/qmk_port_ch582/blob/via/qmk_porting/protocol/extra_keycode.h#L51), you may consider using `NEW_SAFE_RANGE` instead.
```suggestion
    CK_OSMD = NEW_SAFE_RANGE,
```

2023-05-24 02:41 UTC, Huckies commented on qmk_porting/keyboards/imk64/keymaps/jactry/keymap.c
> +bool rgb_matrix_indicators_advanced_user(uint8_t led_min, uint8_t led_max) {
If `led_min` and `led_max` is not respected, I would recommend using `rgb_matrix_indicators_kb()` instead.

2023-05-27 14:11 UTC, jactry commented
I pushed an update.
Thanks for the review!

2023-05-29 07:49 UTC, Huckies approved these changes

2023-05-29 07:49 UTC, merged